#!/usr/bin/env python3
"""Generate fused constant tables for the OpenCL kernel.

A2 — block_perm_sbox = block_perm ∘ block_sbox  (256-entry u8 table)
     block_decrypt then does `W[6] ^= block_perm_sbox[idx]` instead of
     `W[6] ^= block_perm[block_sbox[idx]]`, halving the per-round block LUTs.

Usage: python3 tools/fused_tables.py [--verify-only]
       emits the generated table to stdout; --verify-only reads the kernel
       and compares block_perm_sbox[x] against block_perm[block_sbox[x]].
"""
from __future__ import annotations
import re, sys, pathlib

KERNEL = pathlib.Path(__file__).resolve().parent.parent / "src" / "aycwabtu.cl"


def parse_u8_array(src: str, name: str, size: int) -> list[int]:
    m = re.search(rf"{name}\[{size}\]\s*=\s*\{{([^}}]+)\}}", src, re.DOTALL)
    if not m:
        raise SystemExit(f"table {name}[{size}] not found in kernel")
    vals = [int(x.strip().rstrip(","), 16)
            for x in m.group(1).split() if x.strip().startswith("0x")]
    if len(vals) != size:
        raise SystemExit(f"{name}: got {len(vals)} entries, expected {size}")
    return vals


def emit_table(name: str, vals: list[int]) -> str:
    lines = [f"__constant u8 {name}[{len(vals)}] = {{"]
    for i in range(0, len(vals), 16):
        chunk = vals[i:i + 16]
        lines.append("    " + ", ".join(f"0x{v:02x}" for v in chunk) + ",")
    lines.append("};")
    return "\n".join(lines)


def main() -> int:
    verify_only = "--verify-only" in sys.argv[1:]

    src = KERNEL.read_text()
    sbox = parse_u8_array(src, "block_sbox", 256)
    perm = parse_u8_array(src, "block_perm", 256)

    fused = [perm[sbox[i]] for i in range(256)]
    unique = len(set(fused))

    if verify_only:
        m = re.search(r"block_perm_sbox\[256\]\s*=\s*\{([^}]+)\}", src, re.DOTALL)
        if not m:
            print("NO block_perm_sbox table present in kernel"); return 1
        on_disk = [int(x.strip().rstrip(","), 16)
                   for x in m.group(1).split() if x.strip().startswith("0x")]
        diffs = sum(1 for i in range(256) if on_disk[i] != fused[i])
        print(f"fused table: {len(on_disk)} entries, unique={len(set(on_disk))}, "
              f"errors vs generated={diffs}")
        return 0 if diffs == 0 else 1

    if unique != 256:
        print(f"WARN: fused table not a permutation ({unique}/256 unique)",
              file=sys.stderr)

    print("// Auto-generated by tools/fused_tables.py — do not hand-edit.")
    print("// Fusion: block_perm_sbox[x] = block_perm[block_sbox[x]]")
    print("// block_decrypt indexes with pre-sbox idx = kk[i] ^ W[6].")
    print(emit_table("block_perm_sbox", fused))
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
